; Global Symbol Definitions
DEFAULT_DMG_PALETTE  EQU %11100100
STACK_SIZE           EQU $10

; Menu Symbol Definitions
MENU_1PLAYER_Y       EQU 120
MENU_2PLAYER_Y       EQU 136

MENU_FADEIN_TIMEOUT  EQU 5

; Main Gameplay Symbol Definitions
GAMEPLAY_TILE_EMPTY  EQU 8
CURSOR_BASE_POS_Y    EQU 30
CURSOR_BASE_POS_X    EQU 60
FIELD_SQUARE_WIDTH   EQU 24

AI_TURN_TIMEOUT      EQU 60

CURSOR_ANIM_TIMEOUT  EQU 40
WIN_ANIM_TIMEOUT     EQU 100
WIN_SYM_ANIM_TIMEOUT EQU 3
SYM_ANIM_MAX_SPEED   EQU 3
SYM_ANIM_OFF_X       EQU 2
SYM_ANIM_OFF_Y       EQU 5