; Menu Symbol Definitions
MENU_1PLAYER_Y       EQU 120
MENU_2PLAYER_Y       EQU 136

; Main Gameplay Symbol Definitions
CURSOR_ANIM_TIMEOUT  EQU 40
WIN_ANIM_TIMEOUT     EQU 100
WIN_SYM_ANIM_TIMEOUT EQU 3
SYM_ANIM_MAX_SPEED   EQU 3
SYM_ANIM_OFF_X       EQU 2
SYM_ANIM_OFF_Y       EQU 5